 - name: Check to see if nasm is installed
   shell: command -v nasm >/dev/null 2>&1
   ignore_errors: yes
   register: nasm_is_installed
  
 - debug: msg="{{ nasm_is_installed.rc }}" # it returns rc 1
 - debug: var=nasm_is_installed

 - name:  get nasm
   unarchive:
     src: http://www.nasm.us/pub/nasm/releasebuilds/2.13.02/nasm-2.13.02.tar.bz2
     dest: "{{ ffmpeg_source_dir }}"
     remote_src: yes
 
 - name: compile nasm
   shell: 'cd {{ ffmpeg_source_dir }}/nasm-2.13.02; {{ item }}'
   with_items:
      - ./autogen.sh
      - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }}
      - make
      - make install
      - make distclean
   when: nasm_is_installed.rc != 0
